[package]
name = "resume"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
minify-html = "0.18.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "0.9.8", features = ["preserve_order"] }
